// data.js - App ka saara data yahan hai (Corrected Artist IDs)

const artists = [
  {
    id: 1,
    name: "Arijit Singh",
    image: "https://i.scdn.co/image/ab6761610000e5eb5ba2d75eb08a2d672f9b69b7",
    tagline: "Popular Indian Singer",
  },
  {
    id: 2,
    name: "Diljit Dosanjh",
    image:
      "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da845bd3fc52a142f8f043e7ffe6",
    tagline: "Punjabi superstar",
  },
  {
    id: 3,
    name: "Shreya Ghoshal",
    image:
      "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84f2836295d5df39844017c8a3",
    tagline: "Queen of Melody",
  },
  {
    id: 4,
    name: "Karan Aujla",
    image: "https://i.scdn.co/image/ab6761610000e5eb2a354a64d9c5c602db0be2a4",
    tagline: "Latest Punjabi sensation",
  },
  {
    id: 5,
    name: "Neha Kakkar",
    image:
      "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da847725cb48385b97ed44665281",
    tagline: "Bollywood's most loved voice",
  },
  {
    id: 6,
    name: "Annural Khalid & Maanu",
    image: "https://i.scdn.co/image/ab67616d0000b2731344800458a38197bfc721f3",
    tagline: "Pakistani indie duo",
  },
  {
    id: 7,
    name: "Amrita Kak",
    image: "https://i.scdn.co/image/ab6761610000e5eb5a6250357ea440e6e541bb5d",
    tagline: "Indian playback singer",
  },
  {
    id: 8,
    name: "Sabrina Carpenter",
    image: "https://i.scdn.co/image/ab67616d0000b273fd8d7a8d96871e791cb1f626",
    tagline: "American pop star",
  },
  {
    id: 9,
    name: "Haider Ali",
    image: "https://i.scdn.co/image/ab67616d00001e024e581ac561de278278ae5939",
    tagline: "Pakistani singer",
  },
  {
    id: 10,
    name: "Dua Lipa",
    image: "https://i.scdn.co/image/ab67616d0000b2734bc66095f8a70bc4e6593f4f",
    tagline: "British pop artist",
  },
  {
    id: 11,
    name: "Aditya Rikhari",
    image: "https://i.scdn.co/image/ab6761610000e5eb482c8b15eab378fdebc5e05e",
    tagline: "Indian singer-songwriter",
  },
  {
    id: 12,
    name: "Ed Sheeran",
    image:
      "https://cdn.britannica.com/17/249617-050-4575AB4C/Ed-Sheeran-performs-Rockefeller-Plaza-Today-Show-New-York-2023.jpg",
    tagline: "British singer-songwriter",
  },
  {
    id: 13,
    name: "The Kid Laroi & Justin Bieber",
    image: "https://i.scdn.co/image/ab6761610000517486e362deb9f22566331fbdeb",
    tagline: "Pop collaboration",
  },
  {
    id: 14,
    name: "Bhoomi & Manikk",
    image: "https://i.scdn.co/image/ab67616d0000b273d7f30b73e50b78e78e317b17",
    tagline: "Indian folk singers",
  },
  {
    id: 15,
    name: "B Praak",
    image: "https://i.scdn.co/image/ab6761610000e5ebfd469e9e949eab38a6169a42",
    tagline: "Renowned Punjabi playback singer",
  },
  {
    id: 16,
    name: "Jass Manak",
    image:
      "https://image-cdn-ak.spotifycdn.com/image/ab67706c0000da84715a39a3af64a09058fe0ef9",
    tagline: "Popular Punjabi singer",
  },
  {
    id: 17,
    name: "Yo Yo Honey Singh",
    image: "https://i.scdn.co/image/ab6761610000e5ebbc7e4fffd515b47ff1ebbc1f",
    tagline: "Pioneering Punjabi rapper",
  },
  {
    id: 18,
    name: "Inder Chahal",
    image: "https://i.scdn.co/image/ab6761610000e5ebc40600e02356cc86f0debe84",
    tagline: "Punjabi singer",
  },
];

const songs = [
  {
    id: 1,
    title: "Aee Jii Oo Jii",
    artistId: null,
    file: "Aee Jii Oo Jii.mp3",
    artist: "Kishor Kumar",
  },
  {
    id: 2,
    title: "Beautiful Billo",
    artistId: 2,
    file: "Beautiful Billo.mp3",
    artist: "Diljit Dosanjh, Tru-Skool",
  },
  {
    id: 3,
    title: "Disco Singh",
    artistId: 2,
    file: "Disco Singh.mp3",
    artist: "Diljit Dosanjh",
  },
  {
    id: 4,
    title: "Faisley",
    artistId: 15,
    file: "Faisley.mp3",
    artist: "B Praak",
  },
  {
    id: 5,
    title: "Happy Birthday",
    artistId: 2,
    file: "Happy Birthday.mp3",
    artist: "Diljit Dosanjh",
  },
  {
    id: 6,
    title: "Latto",
    artistId: 2,
    file: "Latto.mp3",
    artist: "Diljit Dosanjh",
  },
  {
    id: 7,
    title: "Naina",
    artistId: 2,
    file: "Naina_Diljit_Dosanjh.mp3",
    artist: "Diljit Dosanjh",
  },
  {
    id: 8,
    title: "Sweetoo",
    artistId: 16,
    file: "Sweetoo.mp3",
    artist: "Jass Manak",
  },
  {
    id: 9,
    title: "Nasha",
    artistId: 18,
    file: "128-Nasha - Raid 2 128 Kbps.mp3",
    artist: "Inder Chahal",
  },
  {
    id: 10,
    title: "O Maahi",
    artistId: 1,
    file: "128-O Maahi - Dunki 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 11,
    title: "Ruaan",
    artistId: 1,
    file: "128-Ruaan - Tiger 3 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 12,
    title: "100 Million",
    artistId: 4,
    file: "128-100 Million - Karan Aujla 128 Kbps.mp3",
    artist: "Karan Aujla",
  },
  {
    id: 13,
    title: "Aaj Ki Raat",
    artistId: 3,
    file: "128-Aaj Ki Raat - Stree 2 128 Kbps.mp3",
    artist: "Shreya Ghoshal",
  },
  {
    id: 14,
    title: "Aaj Se Teri",
    artistId: 1,
    file: "128-Aaj Se Teri - Padman 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 15,
    title: "Abrars Entry Jamal Kudu",
    artistId: null,
    file: "128-Abrars Entry Jamal Kudu - Animal 128 Kbps.mp3",
    artist: "Various Artists",
  },
  {
    id: 16,
    title: "Arjan Vailly",
    artistId: 2,
    file: "128-Arjan Vailly - Animal 128 Kbps.mp3",
    artist: "Diljit Dosanjh",
  },
  {
    id: 17,
    title: "Baarish Ke Aane Se",
    artistId: 3,
    file: "128-Baarish Ke Aane Se - Shreya Ghoshal 128 Kbps.mp3",
    artist: "Shreya Ghoshal",
  },
  {
    id: 18,
    title: "Chor Bazari Phir Se",
    artistId: 3,
    file: "128-Chor Bazari Phir Se - Bhool Chuk Maaf 128 Kbps.mp3",
    artist: "Shreya Ghoshal",
  },
  {
    id: 19,
    title: "Gaadi Kaali",
    artistId: 5,
    file: "128-Gaadi Kaali - Neha Kakkar 128 Kbps.mp3",
    artist: "Neha Kakkar",
  },
  {
    id: 20,
    title: "Hua Main",
    artistId: 1,
    file: "128-Hua Main - Animal 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 21,
    title: "Hum Toh Deewane",
    artistId: 1,
    file: "128-Hum Toh Deewane - Yasser Desai 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 22,
    title: "Ishq Jaisa Kuch",
    artistId: 3,
    file: "128-Ishq Jaisa Kuch - Fighter 128 Kbps.mp3",
    artist: "Shreya Ghoshal",
  },
  {
    id: 23,
    title: "Lutt Putt Gaya",
    artistId: 1,
    file: "128-Lutt Putt Gaya - Dunki 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 24,
    title: "Sher Khul Gaye",
    artistId: 1,
    file: "128-Sher Khul Gaye - Fighter 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 25,
    title: "Sooraj Hi Chhaon Banke",
    artistId: 3,
    file: "128-Sooraj Hi Chhaon Banke - Salaar 128 Kbps.mp3",
    artist: "Shreya Ghoshal",
  },
  {
    id: 26,
    title: "Tu Hain Toh Main Hoon",
    artistId: 1,
    file: "128-Tu Hain Toh Main Hoon - Sky Force 128 Kbps.mp3",
    artist: "Arijit Singh",
  },
  {
    id: 27,
    title: "Ilzaam",
    artistId: 4,
    file: "320-Ilzaam - Jewel Thief The Heist Begins 320 Kbps.mp3",
    artist: "Karan Aujla",
  },
  {
    id: 28,
    title: "Hass Hass",
    artistId: 2,
    file: "Hass_Hass_Diljit_Dosanjh_Sia.mp3",
    artist: "Diljit Dosanjh & Sia",
  },
  {
    id: 29,
    title: "Jhol",
    artistId: 6,
    file: "Jhol_Maanu_Annural_Khalid.mp3",
    artist: "Maanu & Annural Khalid",
  },
  {
    id: 30,
    title: "Russian Bandana",
    artistId: 4,
    file: "Russian_Bandana_Dhanda_Nyoliwala.mp3",
    artist: "Karan Aujla",
  },
  {
    id: 31,
    title: "Character Dheela",
    artistId: 7,
    file: "Character Dheela.mp3",
    artist: "Neeraj Shridhar, Amrita Kak",
  },
  {
    id: 32,
    title: "Espresso",
    artistId: 8,
    file: "Espresso.mp3",
    artist: "Sabrina Carpenter",
  },
  {
    id: 33,
    title: "Heer",
    artistId: 9,
    file: "Heer.mp3",
    artist: "Ali Raza & Haider Ali",
  },
  {
    id: 34,
    title: "Levitating",
    artistId: 10,
    file: "Levitating.mp3",
    artist: "Dua Lipa",
  },
  {
    id: 35,
    title: "Sahiba",
    artistId: 11,
    file: "Sahiba.mp3",
    artist: "Aditya Rikhari",
  },
  {
    id: 36,
    title: "Sapphire",
    artistId: 12,
    file: "Sapphire.mp3",
    artist: "Ed Sheeran",
  },
  {
    id: 37,
    title: "Stay Justin",
    artistId: 13,
    file: "Stay Justin.mp3",
    artist: "The Kid Laroi & Justin Bieber",
  },
  {
    id: 38,
    title: "Jogan",
    artistId: 14,
    file: "Jogan.mp3",
    artist: "Bhoomi & Manikk",
  },
  {
    id: 39,
    title: "Angreji Beat",
    artistId: 17,
    file: "Angreji Beat.mp3",
    artist: "Yo Yo Honey Singh",
  },
  {
    id: 40,
    title: "Bonita Glory",
    artistId: 17,
    file: "Bonita Glory.mp3",
    artist: "Yo Yo Honey Singh",
  },
  {
    id: 41,
    title: "Millionaire Glory",
    artistId: 17,
    file: "Millionaire Glory.mp3",
    artist: "Yo Yo Honey Singh",
  },
  {
    id: 42,
    title: "Jatt Mehkma",
    artistId: 17,
    file: "Jatt Mehkma.mp3",
    artist: "Yo Yo Honey Singh",
  },
];
